let tree_topic_elements = [
    {
        parentsName: "root",
        parrentAttr: "class",
        type: "div",
        attr: "class",
        attrname: "container",
    },
    {
        parentsName: "container",
        parrentAttr: "class",
        type: "h2",
        attr: "class",
        attrname: "todo_title",
        text: "My todo list",
    },
    {
        parentsName: "container",
        parrentAttr: "class",
        type: "div",
        attr: "class",
        attrname: "todo_hat",
    },
    {
        parentsName: "todo_hat",
        parrentAttr: "class",
        type: "div",
        attr: "class",
        attrname: "block_content",
    },
];
const task = [
    {
        parentsName: "todo_hat",
        parrentAttr: "class",
        taskNumber: "0",
        type: "div",
        attr: "class",
        attrname: "todo_task",
        attr1: "id",
        attrname1: "task2",
    },
    {
        parentsName: "todo_task",
        parrentAttr: "class",
        parentId: "task2",
        type: "div",
        attr: "class",
        attrname: "select-box",
        attr1: "id",
        attrname1: "task2_elem2",
    },
    {
        parentsName: "select-box",
        parrentAttr: "class",
        parentId: "task2_elem2",
        type: "input",
        attr: "type",
        attrname: "checkbox",
        attr1: "class",
        attrname1: "box",
        attr2: "id",
        attrname2: "task2_elem3",
    },
    {
        parentsName: "todo_task",
        parrentAttr: "class",
        parentId: "task2",
        type: "div",
        attr: "class",
        attrname: "text_container",
        attr1: "id",
        attrname1: "task2_elem4",
    },
    {
        parentsName: "text_container",
        parrentAttr: "class",
        parentId: "task2_elem4",
        type: "p",
        attr: "class",
        attrname: "text_task",
        attr1: "id",
        attrname1: "task2_elem5",
    },
    {
        parentsName: "todo_task",
        parrentAttr: "class",
        parentId: "task2",
        type: "div",
        attr: "class",
        attrname: "select-block",
        attr1: "id",
        attrname1: "task2_elem6",
    },
    {
        parentsName: "select-block",
        parrentAttr: "class",
        parentId: "task2_elem6",
        type: "button",
        attr: "class",
        attrname: "del",
        attr1: "id",
        attrname1: "task2_elem7",
        text: "X",
    },
    {
        parentsName: "select-block",
        parrentAttr: "class",
        parentId: "task2_elem6",
        type: "p",
        attr: "class",
        attrname: "time1",
        attr1: "id",
        attrname1: "task2_elem8",
        text: "xx.xx.xx",
    },
];

export { tree_topic_elements, task };
